- hosts: localhost
  connection: local
  vars:
  vars_prompt:

    - name: user
      prompt: "What is the name of the account you wish to create?"
      private: no

  tasks:
  - name: Add Spotify repo key
    apt_key:
      url: "https://download.spotify.com/debian/pubkey.gpg"
      state: present

  - name: Add Atom repo key
    apt_key:
      url: 'https://packagecloud.io/AtomEditor/atom/gpgkey'
      state: present

  - name: Add Spotify repo
    apt_repository:
      repo: 'deb http://repository.spotify.com stable non-free'
      state: present

  - name: Add Atom repo
    apt_repository:
      repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
      filename: atom
      state: present

  - name: Upgrade existing packages, clear unused dependencies
    apt:
      upgrade: yes
      autoremove: yes

  - name: Install apps
    ignore_errors: yes
    apt:
      update_cache: yes
      name: rsync,vim,htop,atom,zsh,python-pexpect,tlp,tlp-rdw,powertop,papirus-icon-theme,spotify-client,evolution,libreoffice,ansible,git,screen,vim-gtk,openssh-server
      state: present

## User being created with variables input at first prompts.
  - name: Add the user {{ user }}
    user:
      name: "{{ user }}"
      groups: sudo
      create_home: yes
      shell: /bin/zsh

## Comment out if not running against desktop.
  - name: Start TLP for power savings on portable computers
    service:
      name: tlp
      state: started
      enabled: yes

  - name: Enable sshd for SSHing into this computer
    service:
      name: sshd
      state: started
      enabled: yes

  - name: Set GNOME preferences. Separately run "dconf load / < saved_settings" to take affect
    copy:
      src: "files/brad-settings.dconf"
      dest: /home/{{ user }}/saved_settings.dconf
      owner: "{{ user }}"
      mode: '0644'
      group: "{{ user }}"

  - name: Implement no-password sudo
    lineinfile:
      path: /etc/sudoers.d/{{ user }}
      line: '{{ user }} ALL=(ALL:ALL) NOPASSWD: ALL'
      create: yes
      validate: /usr/sbin/visudo -csf %s

  - name: Placing .zshrc in new user's home directory
    copy:
      src: "files/zshrc"
      dest: /home/{{ user }}/.zshrc
      owner: "{{ user }}"
      mode: '0644'

  - name: Importing Manjaro's excellent ZSH plugins to make your life better
    synchronize:
      src: "files/zsh"
      dest: /usr/share/

  - name: Importing Yaru theme. You know you want it.
    synchronize:
      src: "files/yaru/icons"
      dest: /usr/share

  - synchronize: 
      src: "files/yaru/themes"
      dest: /usr/share

  - name: Create .config folder in home directory to place setup-done file
    file:
      path: "/home/{{ user }}/.config"
      state: directory
      owner: "{{ user }}"

  - name: Touch gnome-initial-setup-done in /home/{{ user }}/.config. This will allow the new account to slip the GNOME setup prompt.
    file:
      path: "/home/{{ user }}/.config/gnome-initial-setup-done"
      state: touch
      owner: "{{ user }}"
      mode: '0644'

  - name: Clean up 'df' output by excluding snap and tmpfs from output
    lineinfile:
      path: /home/{{ user }}/.zshrc
      line: alias dfh='df -h -x squashfs -x tmpfs'
