- hosts: localhost
  connection: local
  vars:
  vars_prompt:

    - name: user
      prompt: "What is the name of the account you wish to create?"
      private: no

    - name: password
      prompt: "Enter the password to be applied to the account."

  tasks:
  - name: Install apps, ignoring errors
    dnf:
      name: 
        - vim
        - htop
        - zsh
        - python-pexpect
        - gnome-tweaks
        - gnome-tweak-tool
        - tlp
        - tlp-rdw
        - libreoffice
        - git
        - screen
        - gvim
        - openssh-server
      state: latest

## User being created with variables input at first prompts.
  - name: Add the user "{{ user }}"
    user:
      name: "{{ user }}"
      groups: wheel
      create_home: yes
      shell: /bin/zsh

  - name: Set user password
    expect:
      command: /bin/bash -c 'passwd "{{ user }}"'
      responses:
        password: "{{ password }}"
        password: "{{ password }}"

## Comment out if not running against desktop.
  - name: Start TLP for power savings on portable computers
    service:
      name: tlp
      state: started
      enabled: yes

  - name: Enable sshd for SSHing into this computer
    service:
      name: sshd
      state: started
      enabled: yes

  - name: Implement no-password sudo
    lineinfile:
      path: /etc/sudoers.d/{{ user }}
      line: '"{{ user }}" ALL=(ALL:ALL) NOPASSWD: ALL'
      create: yes
      validate: /usr/sbin/visudo -csf %s

  - name: Placing .zshrc in new user's home directory
    copy:
      src: "files/zshrc"
      dest: /home/{{ user }}/.zshrc
      owner: "{{ user }}"
      mode: '0644'

  - name: Importing Manjaro's excellent ZSH plugins to make your life better
    synchronize:
      src: "files/zsh"
      dest: /usr/share/

  - name: Clean up 'df' output by excluding snap and tmpfs from output
    lineinfile:
      path: /home/{{ user }}/.zshrc
      line: alias dfh='df -h -x squashfs -x tmpfs'
